# Generated by Django 3.2.19 on 2023-06-05 06:37

import authentication.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20230518_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.users.upload_to),
        ),
    ]
