name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    env:
      # This token is provided by Actions and is scoped to the repository that contains your workflow file
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # This is the project ID of your Google Cloud project
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      # This is the service account key file that you created in the Google Cloud console
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v1.2.7
      with:
        deliverables: app.yaml
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Test App Engine Deployment
      run: curl "${{ steps.deploy.outputs.url }}"
